build:
    maxIssues: 0

complexity:
    LongMethod:
        active: true
        threshold: 50
    CyclomaticComplexMethod:
        active: true
        threshold: 8
    LongParameterList:
        active: true
        functionThreshold: 6
        constructorThreshold: 7
        ignoreDefaultParameters: true
    NestedBlockDepth:
        active: true
        threshold: 4
    TooManyFunctions:
        active: true
        thresholdInFiles: 15
        thresholdInClasses: 15

formatting:
    Indentation:
        active: false
    FunctionNaming:
        active: false
    MaximumLineLength:
        active: true
        maxLineLength: 120

naming:
    FunctionNaming:
        active: false

performance:
    ForEachOnRange:
        active: true

potential-bugs:
    EqualsWithHashCodeExist:
        active: true
    UnsafeCallOnNullableType:
        active: true

style:
    MaxLineLength:
        active: true
        maxLineLength: 120
    MagicNumber:
        active: false
    UnusedPrivateMember:
        active: true
        ignoreAnnotated:
            - 'Preview'
    ReturnCount:
        active: true
        max: 3
